# Generated by Django 2.2.14 on 2020-12-09 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200731_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='auctionhead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('desc', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('auction_head_image', models.ImageField(upload_to='uploads/')),
                ('active_bool', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='auctionitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=64)),
                ('desc', models.TextField()),
                ('starting_bid', models.IntegerField()),
                ('image_url', models.CharField(blank=True, default=None, max_length=228, null=True)),
                ('category', models.CharField(max_length=64)),
                ('active_bool', models.BooleanField(default=True)),
                ('end_date', models.DateTimeField()),
                ('auctionhead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.auctionhead')),
            ],
        ),
    ]
