# Generated by Django 2.2.14 on 2021-01-12 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auctionhead_auctionitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionhead',
            name='highlights',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='auctionhead',
            name='location',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='auctionhead',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='auctionhead',
            name='terms',
            field=models.TextField(null=True),
        ),
    ]
