# Generated by Django 2.2.14 on 2021-01-12 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20210112_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=64)),
                ('desc', models.CharField(max_length=512)),
                ('active_bool', models.BooleanField(default=True)),
            ],
        ),
    ]
