# Generated by Django 2.2.14 on 2021-01-13 00:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20210112_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionhead',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
