# Generated by Django 2.2.14 on 2021-01-13 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20210112_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='watch_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.auctionitem'),
        ),
        migrations.AlterField(
            model_name='winner',
            name='bid_win_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.auctionitem'),
        ),
    ]
