# Generated by Django 2.2.14 on 2021-01-13 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20210112_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
