# Generated by Django 2.2.14 on 2021-01-18 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auctionitem_image1'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='current_bid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
