# Generated by Django 2.2.14 on 2021-01-19 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auctionitem_current_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='reserve_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bids',
            name='max_bid',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='bidincrements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up_to_amount', models.IntegerField()),
                ('bid_increment', models.IntegerField()),
                ('active_bool', models.BooleanField(default=True)),
                ('auctionhead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.auctionhead')),
            ],
        ),
    ]
